import {beforeEach,describe,expect,it,vi} from "vitest";
import {emptyDeclarations,emptySalary,emptyScope,profileSchema,type Filing} from "../src/lib/domain";
import {initialConversation,nextChatQuestion,chatReady,maskSensitive,effectiveProfile} from "../src/lib/chat";

const mocks=vi.hoisted(()=>({local:false,extract:vi.fn(),save:vi.fn(),profile:vi.fn(),audit:vi.fn()}));
vi.mock("@/server/config",()=>({localMode:()=>mocks.local,env:(name:string)=>process.env[name]}));
vi.mock("@/server/repository",()=>({saveFiling:mocks.save,getProfile:mocks.profile,audit:mocks.audit,auditEvent:(ownerId:string,filingId:string,action:string,requestId:string)=>({ownerId,filingId,action,requestId})}));
vi.mock("@/server/chat-ai",()=>({interpretAnswer:mocks.extract}));
import {applyChatExtraction,sendChatMessage,connectChatRecords} from "../src/server/chat";
import {fetchAuthorizedRecords} from "../src/server/records";
import {confirmChatReview,viewFiling} from "../src/server/filings";

const profile=profileSchema.parse({name:"Sample Employee",pan:"AAAAA1234A",dateOfBirth:"1985-06-12",address:"Fictional address",postalCode:"110001",bankAccount:"1234567890",ifsc:"ABCD0123456"});
function filing():Filing{return {id:"00000000-0000-4000-8000-000000000001",ownerId:"00000000-0000-4000-8000-000000000002",year:"2026-27",revision:0,createdAt:"2026-09-27T00:00:00Z",updatedAt:"2026-09-27T00:00:00Z",status:"draft",salary:emptySalary(),scope:emptyScope(),declarations:emptyDeclarations(),confirmedFields:[],pending:null,regime:"new",processingConsentAt:"2026-09-27T00:00:00Z",aiConsentAt:null,prefillConsentAt:null,prefill:null,prefillSource:"unavailable",reviewHash:null,reviewConfirmedAt:null,officialReference:null,acknowledgement:null,paymentStatus:"unavailable",submissionKey:null,conversation:initialConversation()};}
function complete(){const f=filing();f.salary={...emptySalary(),employerName:"Example department",employerTan:"ABCD12345E",annualSalary:1500000,salaryTds:100000,savingsInterest:10000,depositInterest:20000,otherTds:0,employerNps:0};f.scope={...emptyScope(),resident:true,under60:true,onlySalaryAndInterest:true,noSpecialCircumstances:true,employerType:"state",wantsDeductions:false};f.conversation!.profileDraft=profile;f.conversation!.fetchAttemptedAt=new Date().toISOString();f.conversation!.connections=[{kind:"tax",status:"ready",reference:"test-reference",detail:"Fictional test source"}];return f;}
beforeEach(()=>{vi.clearAllMocks();vi.unstubAllEnvs();vi.unstubAllGlobals();mocks.local=false;mocks.save.mockImplementation(async(f:Filing)=>f);mocks.profile.mockResolvedValue(profileSchema.parse({}));mocks.audit.mockResolvedValue(undefined);vi.stubEnv("TAX_DATA_GATEWAY_URL","https://gateway.example/");vi.stubEnv("TAX_DATA_GATEWAY_TOKEN","test-only-token");});
describe("fetch-first chat",()=>{
  it("asks for PAN before any financial details",()=>{expect(nextChatQuestion(filing(),profileSchema.parse({}))?.id).toBe("pan");});
  it("requests connections instead of asking a filled profile to be typed again",()=>{expect(nextChatQuestion(filing(),profile)?.id).toBe("connect");});
  it("does not substitute a long form when providers are unavailable",()=>{const f=filing();f.conversation!.profileDraft.pan=profile.pan;f.conversation!.fetchAttemptedAt=new Date().toISOString();expect(nextChatQuestion(f,profileSchema.parse({}))?.id).toBe("connections_unavailable");});
  it("asks zero factual questions when complete supported facts are available",()=>{expect(nextChatQuestion(complete(),profileSchema.parse({}))).toBeNull();expect(chatReady(complete(),profileSchema.parse({}))).toBe(true);expect(complete().confirmedFields).toHaveLength(0);});
  it("asks only the missing interest amount and never infers zero",()=>{const f=complete();f.salary.depositInterest=null;expect(nextChatQuestion(f,profileSchema.parse({}))?.id).toBe("salary.depositInterest");expect(f.salary.depositInterest).toBeNull();});
  it("stops unnecessary follow-ups as soon as an unsupported situation is known",()=>{const f=complete();f.scope.resident=false;f.scope.employerType=null;f.salary.depositInterest=null;expect(nextChatQuestion(f,profileSchema.parse({}))?.id).toBe("assisted");});
  it("uncertain and conflicting values cannot reach review",()=>{const f=complete();f.conversation!.factConfidence["salary.salaryTds"]="low";expect(chatReady(f,profile)).toBe(false);f.conversation!.pendingIssues=["salary.salaryTds: source discrepancy"];expect(nextChatQuestion(f,profile)?.id).toBe("conflict");});
  it("PAN and bank identifiers are masked in visible transcripts",()=>{const result=maskSensitive("PAN AAAAA1234A account 1234567890");expect(result).not.toContain("AAAAA1234A");expect(result).not.toContain("1234567890");});
  it("PAN change clears records and invalidates previous approval",async()=>{const f=complete();f.status="prepared";f.reviewHash="old";const n=await sendChatMessage(f,"BBBBB1234B",false,profile,"test");expect(n.salary.annualSalary).toBeNull();expect(n.conversation!.connections.every(c=>c.status==="not_connected")).toBe(true);expect(n.reviewHash).toBeNull();expect(effectiveProfile(n,profile).name).toBe("");expect(mocks.extract).not.toHaveBeenCalled();});
  it("AI corrections update drafts without silently confirming",()=>{const f=complete();f.reviewHash="old";f.confirmedFields=["salaryTds"];const r=applyChatExtraction(f,{changes:[{section:"salary",key:"salaryTds",value:110000,confidence:"high",evidence:"Explicit correction"}],uncertainties:[]});expect(r.filing.salary.salaryTds).toBe(110000);expect(r.filing.confirmedFields).toEqual([]);expect(r.filing.reviewHash).toBeNull();expect(r.changes).toHaveLength(1);});
  it("invalid AI values cannot enter tax data",()=>{const r=applyChatExtraction(complete(),{changes:[{section:"salary",key:"salaryTds",value:-1,confidence:"high",evidence:"bad"}],uncertainties:[]});expect(r.filing.salary.salaryTds).toBe(100000);expect(r.filing.conversation!.pendingIssues.length).toBeGreaterThan(0);});
  it("a new complete answer resolves the matching uncertainty",()=>{const f=complete();f.conversation!.pendingIssues=["salary.salaryTds: invalid","answer: unclear value"];const r=applyChatExtraction(f,{changes:[{section:"salary",key:"salaryTds",value:50000,confidence:"high",evidence:"Corrected"}],uncertainties:[]});expect(r.filing.conversation!.pendingIssues).toEqual([]);});
  it("review is bound to the exact prepared snapshot and never submits",async()=>{const f=complete();const v=await viewFiling(f);await expect(confirmChatReview(f,"0".repeat(64),"test")).rejects.toMatchObject({code:"review_changed"});const approved=await confirmChatReview(f,v.chatReviewHash,"test");expect(approved.status).toBe("prepared");expect(approved.officialReference).toBeNull();expect(approved.confirmedFields).toContain("annualSalary");});
});
describe("record authorization boundary",()=>{
  it("refuses a fetch without consent",async()=>{await expect(fetchAuthorizedRecords(complete(),profile)).rejects.toMatchObject({code:"consent_required"});});
  it("local sample mode never calls a live provider",async()=>{mocks.local=true;const fetch=vi.fn();vi.stubGlobal("fetch",fetch);const f=complete();const r=await connectChatRecords(f,profile,"test");expect(fetch).not.toHaveBeenCalled();expect(r.conversation!.connections.every(c=>c.status==="unavailable")).toBe(true);});
  it("rejects a provider response for another PAN",async()=>{const f=complete();f.conversation!.recordsConsentAt=new Date().toISOString();vi.stubGlobal("fetch",vi.fn().mockResolvedValue(Response.json({source:"authorized_gateway",subjectPan:"BBBBB1234B",assessmentYear:"2026-27",records:[]})));await expect(fetchAuthorizedRecords(f,profile)).rejects.toMatchObject({code:"taxpayer_mismatch"});});
  it("rejects unapproved authorization redirects",async()=>{const f=complete();f.conversation!.recordsConsentAt=new Date().toISOString();vi.stubGlobal("fetch",vi.fn().mockResolvedValue(Response.json({source:"authorized_gateway",subjectPan:profile.pan,assessmentYear:"2026-27",records:[{kind:"tax",status:"authorization_required",detail:"Consent",authorizationUrl:"https://untrusted.example/"}]})));await expect(fetchAuthorizedRecords(f,profile)).rejects.toMatchObject({code:"unsafe_authorization_url"});});
  it("requires source provenance for ready records",async()=>{const f=complete();f.conversation!.recordsConsentAt=new Date().toISOString();vi.stubGlobal("fetch",vi.fn().mockResolvedValue(Response.json({source:"authorized_gateway",subjectPan:profile.pan,assessmentYear:"2026-27",records:[{kind:"tax",status:"ready",detail:"No evidence"}]})));await expect(fetchAuthorizedRecords(f,profile)).rejects.toMatchObject({code:"missing_provenance"});});
  it("preserves conflicting values instead of silently overwriting",async()=>{const f=complete();f.conversation!.recordsConsentAt=new Date().toISOString();vi.stubGlobal("fetch",vi.fn().mockResolvedValue(Response.json({source:"authorized_gateway",subjectPan:profile.pan,assessmentYear:"2026-27",records:[{kind:"tax",status:"ready",detail:"Test source",reference:"test",receivedAt:new Date().toISOString(),salary:{salaryTds:50000}}]})));const r=await fetchAuthorizedRecords(f,profile);expect(r.salary.salaryTds).toBe(100000);expect(r.conversation!.pendingIssues).toContain("salary.salaryTds: your saved value and tax record differ.");});
});
