import {beforeEach,describe,expect,it,vi} from "vitest";
import {profileSchema} from "../src/lib/domain";
import {pcmToWav} from "../src/lib/audio";
const state=vi.hoisted(()=>({local:true,save:vi.fn(),profile:vi.fn()}));
vi.mock("@/server/config",()=>({localMode:()=>state.local,env:(name:string)=>process.env[name]}));
vi.mock("@/server/repository",()=>({saveFiling:state.save,getProfile:state.profile,auditEvent:()=>({})}));
import {startDemo,populateDemo,submitDemo,verifyDemo,demoValidationIssues} from "../src/server/demo";
import {viewFiling,confirmChatReview,submitFiling,updateFiling} from "../src/server/filings";
import {applyChatExtraction} from "../src/server/chat";
beforeEach(()=>{state.local=true;state.save.mockImplementation(async f=>f);state.profile.mockResolvedValue(profileSchema.parse({}));});
describe("isolated filing simulation",()=>{
  it("complete demo calculates real deterministic amounts and never assigns an official reference",async()=>{const f=populateDemo(await startDemo("owner","complete","test"));const view=await viewFiling(f);expect(view.chatCanReview).toBe(true);expect(view.chatQuestion).toBeNull();expect(view.estimates?.new.estimatedRefund).toBe(22830);expect(f.prefillSource).toBe("unavailable");expect(f.officialReference).toBeNull();expect(f.acknowledgement).toBeNull();});
  it("missing-interest scenario leaves the required value unknown",async()=>{const f=populateDemo(await startDemo("owner","missing-interest","test"));const view=await viewFiling(f);expect(f.salary.depositInterest).toBeNull();expect(view.chatQuestion?.id).toBe("salary.depositInterest");expect(view.chatCanReview).toBe(false);});
  it("upload-first scenario waits for an employee-supplied fictional Form 16",async()=>{
    const f=populateDemo(await startDemo("owner","upload-form16","test"));const view=await viewFiling(f);
    expect(f.salary.annualSalary).toBeNull();expect(f.salary.salaryTds).toBeNull();expect(f.salary.employerName).toBeNull();
    expect(f.salary.savingsInterest).toBe(7200);expect(f.salary.depositInterest).toBeNull();expect(f.scope.wantsDeductions).toBeNull();
    expect(f.conversation?.connections.find(source=>source.kind==="employer")?.status).toBe("not_connected");
    expect(view.chatCanReview).toBe(false);expect(view.chatQuestion?.id).toBe("salary.employerName");
  });
  it("asks about FD interest and home loan after a fictional Form 16, without treating a loan as a deduction",async()=>{
    const f=populateDemo(await startDemo("owner","upload-form16","test"));
    f.salary={...f.salary,employerName:"Demo Department of School Education",employerTan:"DEMO12345A",annualSalary:1520000,salaryTds:110000,employerNps:84000,basicDa:600000,eligible80C:150000,eligible80D:25000,professionalTax:2400,hraExemption:0};
    f.scope.npsIncludedInSalary=true;
    expect((await viewFiling(f)).chatQuestion?.id).toBe("salary.depositInterest");
    f.salary.depositInterest=18000;
    expect((await viewFiling(f)).chatQuestion?.id).toBe("demo.homeLoan");
    const {filing:noLoan}=applyChatExtraction(f,{changes:[{section:"declarations",key:"loans",value:[],confidence:"high",evidence:"User explicitly said no home loan"}],uncertainties:[]});
    expect(noLoan.demo?.homeLoanAnswer).toBe(false);
    expect((await viewFiling(noLoan)).chatQuestion?.id).toBe("wantsDeductions");
    const {filing:hasLoan}=applyChatExtraction(f,{changes:[{section:"declarations",key:"loans",value:["home"],confidence:"high",evidence:"User explicitly disclosed a home loan"}],uncertainties:[]});
    expect(hasLoan.demo?.homeLoanAnswer).toBe(true);
    expect(demoValidationIssues(hasLoan).some(issue=>issue.code==="loan_review")).toBe(true);
  });
  it("finishes the one-question scenario after a conversational interest answer",async()=>{
    const awaitingInterest=populateDemo(await startDemo("owner","missing-interest","test"));
    const {filing:answered}=applyChatExtraction(awaitingInterest,{changes:[{section:"salary",key:"depositInterest",value:18000,confidence:"high",evidence:"User stated annual FD interest from bank statement"}],uncertainties:[]});
    const view=await viewFiling(answered);
    expect(view.chatQuestion).toBeNull();
    expect(view.chatCanReview).toBe(true);
    expect(view.estimates?.new.estimatedRefund).toBe(22830);
    const approved=await confirmChatReview(answered,view.chatReviewHash,"test");
    const submitted=await submitDemo(approved,approved.reviewHash!,"test");
    const verified=await verifyDemo(submitted,"test");
    expect(verified.demo?.phase).toBe("verified");
    expect(verified.demo?.acknowledgement?.simulated).toBe(true);
  });
  it("requires review before demo submission and submission before verification",async()=>{const f=populateDemo(await startDemo("owner","complete","test"));await expect(submitDemo(f,"bad","test")).rejects.toMatchObject({code:"demo_review_required"});await expect(verifyDemo(f,"test")).rejects.toMatchObject({code:"demo_submission_required"});});
  it("acknowledgement is explicitly simulated and cannot enter the real ERI workflow",async()=>{const f=populateDemo(await startDemo("owner","complete","test")),view=await viewFiling(f);const reviewed=await confirmChatReview(f,view.chatReviewHash,"test");const submitted=await submitDemo(reviewed,reviewed.reviewHash!,"test");const verified=await verifyDemo(submitted,"test");expect(verified.demo?.acknowledgement?.number).toMatch(/^DEMO-ACK-/);expect(verified.demo?.acknowledgement?.simulated).toBe(true);expect(verified.officialReference).toBeNull();expect(verified.acknowledgement).toBeNull();await expect(submitFiling(verified,verified.reviewHash!,"test")).rejects.toMatchObject({code:"demo_cannot_file"});});
  it("accepts a sourced conversational correction to fictional interest through demo verification",async()=>{
    const original=populateDemo(await startDemo("owner","complete","test"));
    const {filing:corrected}=applyChatExtraction(original,{changes:[{section:"salary",key:"depositInterest",value:22500,confidence:"high",evidence:"User corrected the fictional bank interest statement"}],uncertainties:[]});
    expect(corrected.salary.depositInterest).toBe(22500);
    expect(demoValidationIssues(corrected).some(issue=>issue.code==="prefill_mismatch")).toBe(false);
    const view=await viewFiling(corrected);
    expect(view.chatCanReview).toBe(true);
    expect(view.estimates?.new.estimatedRefund).not.toBe((await viewFiling(original)).estimates?.new.estimatedRefund);
    const reviewed=await confirmChatReview(corrected,view.chatReviewHash,"test");
    const submitted=await submitDemo(reviewed,reviewed.reviewHash!,"test");
    expect(submitted.salary.depositInterest).toBe(22500);
    expect((await verifyDemo(submitted,"test")).demo?.acknowledgement?.simulated).toBe(true);
  });
  it("clears a prior chat approval when a user edits the reviewed worksheet",async()=>{
    const original=populateDemo(await startDemo("owner","complete","test"));
    const view=await viewFiling(original);
    const approved=await confirmChatReview(original,view.chatReviewHash,"test");
    const edited=await updateFiling(approved,{revision:approved.revision,salary:{...approved.salary,depositInterest:23000}},"test");
    expect(edited.conversation?.confirmedAt).toBeNull();
    expect(edited.reviewConfirmedAt).toBeNull();
    expect(edited.status).toBe("draft");
    await expect(submitDemo(edited,approved.reviewHash!,"test")).rejects.toMatchObject({code:"demo_review_required"});
  });
  it("does not bypass unsupported loans or uncertain claims in the demo",async()=>{const f=populateDemo(await startDemo("owner","complete","test"));f.declarations.loans=["home"];expect(demoValidationIssues(f).some(x=>x.code==="loan_review")).toBe(true);});
  it("cannot create simulations through production mode",async()=>{state.local=false;await expect(startDemo("owner","complete","test")).rejects.toMatchObject({code:"demo_only"});});
  it("WAV output contains correct byte lengths and rejects corrupt PCM",()=>{const pcm=new Uint8Array([0,0,255,127]),wav=pcmToWav(pcm);expect(new TextDecoder().decode(wav.slice(0,4))).toBe("RIFF");expect(wav.length).toBe(48);expect(new DataView(wav.buffer).getUint32(40,true)).toBe(4);expect(()=>pcmToWav(new Uint8Array(3))).toThrow();});
});
