import {describe,expect,it} from "vitest";
import {emptySalary,emptyScope,emptyDeclarations,profileSchema,type Filing} from "../src/lib/domain";
import {initialConversation} from "../src/lib/chat";
import {currentReturnContext} from "../src/server/return-context";
import {isKnowledgeQuestion} from "../src/server/knowledge";
function fixture():Filing{return {id:"test",ownerId:"test",year:"2026-27",revision:1,createdAt:"",updatedAt:"",status:"draft",salary:{...emptySalary(),annualSalary:1440000,salaryTds:100000,savingsInterest:7200,depositInterest:18000,otherTds:1800,employerNps:0},scope:{...emptyScope(),resident:true,under60:true,onlySalaryAndInterest:true,noSpecialCircumstances:true,employerType:"central",wantsDeductions:false},declarations:emptyDeclarations(),confirmedFields:[],pending:null,regime:"new",processingConsentAt:"",aiConsentAt:null,prefillConsentAt:null,prefill:null,prefillSource:"unavailable",reviewHash:null,reviewConfirmedAt:null,officialReference:null,acknowledgement:null,paymentStatus:"unavailable",submissionKey:null,conversation:initialConversation()};}
describe("voice uses current site state",()=>{
  it("rebuilds amounts and code-calculated estimates after a saved edit",()=>{const f=fixture(),old=currentReturnContext(f);f.salary.depositInterest=22500;f.revision++;const updated=currentReturnContext(f);expect(updated.salary.depositInterest).toBe(22500);expect(updated.revision).toBe(2);expect(updated.calculations!.new.coreTaxLiability).toBeGreaterThan(old.calculations!.new.coreTaxLiability);expect(updated.officialSubmissionConfirmed).toBe(false);});
  it("keeps raw PAN and refund-account values out of the model snapshot",()=>{const f=fixture();f.conversation!.profileDraft={pan:"AAPPS1234A",bankAccount:"1234567890"};const snapshot=currentReturnContext(f,profileSchema.parse({}));expect(JSON.stringify(snapshot)).not.toContain("AAPPS1234A");expect(JSON.stringify(snapshot)).not.toContain("1234567890");expect(snapshot.profileCompleteness.pan).toBe(true);});
  it("does not manufacture calculations for incomplete data",()=>{const f=fixture();f.salary.depositInterest=null;const snapshot=currentReturnContext(f);expect(snapshot.calculations).toBeNull();expect(snapshot.validations.some(x=>x.field==="depositInterest")).toBe(true);});
  it("recognizes questions about current values without treating them as edits",()=>{expect(isKnowledgeQuestion("मेरी एफडी का ब्याज अब कितना दर्ज है?")).toBe(true);expect(isKnowledgeQuestion("What is my current refund estimate?")).toBe(true);expect(isKnowledgeQuestion("मेरी एफडी का ब्याज बदलकर पच्चीस हजार कर दीजिए।")).toBe(false);});
});
