"use client";
import Link from "next/link";
import {useEffect,useRef,useState} from "react";
import {ArrowRight,ArrowUpRight,Check,CheckCircle2,ChevronDown,Download,FileCheck2,Landmark,Link2,Loader2,LockKeyhole,Mic,SendHorizontal,ShieldCheck,Sparkles,Square,X} from "lucide-react";
import {api,post,type FilingView,type Session} from "./client-api";
import {connectionLabels,initialConversation} from "@/lib/chat";
import {inr} from "@/lib/domain";
import {useVoiceSession,VoiceDraftNotice} from "./voice-session";

export function ChatInterface({id,session,onSessionChange}:{id?:string;session:Session;onSessionChange:()=>Promise<void>}){
  const [view,setView]=useState<FilingView|null>(null),[text,setText]=useState(""),[busy,setBusy]=useState(""),[error,setError]=useState("");
  const [consent,setConsent]=useState(false),[showConsent,setShowConsent]=useState(false),[aiConsent,setAiConsent]=useState(false),[showReview,setShowReview]=useState(false),[submissionConsent,setSubmissionConsent]=useState(false);
  const bottom=useRef<HTMLDivElement>(null),input=useRef<HTMLTextAreaElement>(null),mounted=useRef(true);
  const accept=(v:FilingView)=>{setView(v);setConsent(true);setAiConsent(old=>old||Boolean(v.filing.aiConsentAt));setSubmissionConsent(false);};
  useEffect(()=>{let active=true;if(!id){setView(null);setConsent(false);return;}
    setBusy("Opening your conversation");api<FilingView>(`filings/${id}`).then(v=>{if(active)accept(v);}).catch(e=>active&&setError(e.message)).finally(()=>active&&setBusy(""));return()=>{active=false;};
  },[id]);
  useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
  useEffect(()=>{if(view?.filing.conversation?.messages.length)bottom.current?.scrollIntoView({behavior:"smooth",block:"end"});},[view?.filing.revision,busy]);
  const voiceSession=useVoiceSession();
  useEffect(()=>{const update=voiceSession.lastUpdate;if(update&&update.filingId===id)setView(current=>!current||update.view.filing.revision>current.filing.revision?update.view:current);},[voiceSession.lastUpdate,id]);
  const f=view?.filing,c=f?.conversation??initialConversation();
  const aiAllowed=aiConsent||Boolean(f?.aiConsentAt);const locked=f&&!['draft','prepared'].includes(f.status);
  async function run(label:string,fn:()=>Promise<void>){setBusy(label);setError("");try{await fn();}catch(e){setError((e as Error).message);}finally{if(mounted.current)setBusy("");}}
  async function startLocal(){await run("Opening a private sample session",async()=>{await post("auth/local",{sampleDataOnly:true});await onSessionChange();setShowConsent(true);});}
  async function send(answer=text,approved=consent){
    if(!answer.trim()||busy)return;
    if(!session.user){setError("Sign in to keep your tax conversation private. In this local workspace, you can start a sample session below.");return;}
    if(!approved&&!f){setText(answer);setShowConsent(true);return;}
    await run("Working on your answer",async()=>{
      const current=view??await post<FilingView>("filings",{processingConsent:true});accept(current);
      const result=await post<FilingView>(`filings/${current.filing.id}/chat`,{text:answer,aiConsent:aiAllowed,revision:current.filing.revision});accept(result);setText("");setShowConsent(false);
      if(!id)window.history.replaceState(null,"",`/filings/${result.filing.id}`);
    });
  }
  async function begin(){setConsent(true);setShowConsent(false);await send(text.trim()||"I need to file my ITR",true);}
  async function connect(){if(!f)return;await run("Checking your authorized record connections",async()=>accept(await post<FilingView>(`filings/${f.id}/connect-records`,{consent:true,revision:f.revision})));}
  const noMessages=!c.messages.length;
  const proposedRegime=view?.recommendedRegime??f?.regime??"new";
  const currentEstimate=view?.estimates?.[proposedRegime];
  return <div className="chat-workspace">
    <div className="chat-page-meta"><span><LockKeyhole size={13}/> PRIVATE CONVERSATION · निजी बातचीत</span><span>FY 2025–26 <span className="chat-meta-dot">·</span> AY 2026–27</span></div>
    {noMessages&&<section className="chat-welcome"><div className="chat-sun"><Sparkles size={30}/></div><div className="chat-eyebrow">आपका अपना टैक्स साथी</div><h1>Just say, “File my ITR.”</h1><p className="chat-welcome-hi" lang="hi">बस बात कीजिए। बाकी हम संभालेंगे।</p><p>We connect your records, prepare the details, and ask only what’s missing.<br className="desktop-break"/> No tax forms to fill. No routine document uploads.</p><div className="chat-start-actions"><button onClick={()=>send("I need to file my ITR")} className="button" disabled={!!busy}>File my ITR · शुरू करें <ArrowRight size={17}/></button><Link href="/connections" className="text-button">How records are connected <ArrowUpRight size={15}/></Link></div><div className="chat-mini-journey"><span><span>1</span>PAN & permission</span><i/><span><span>2</span>We fetch & prepare</span><i/><span><span>3</span>You approve & verify</span></div></section>}
    {f&&<VoiceDraftNotice filingId={f.id} revision={f.revision}/>}<div className="chat-thread" role="log" aria-label="Tax preparation conversation" aria-live="polite">
      {c.messages.map(message=><article key={message.id} className={`chat-message ${message.role}`}><div className="chat-message-avatar">{message.role==="assistant"?<Sparkles size={17}/>:"You"}</div><div className="chat-message-content"><div className="chat-author">{message.role==="assistant"?"Saral · सरल":"You · आप"}</div><p>{message.text}</p></div></article>)}
      {f&&view?.chatQuestion&&c.messages.at(-1)?.text!==view.chatQuestion.text&&<article className="chat-message assistant current-question"><div className="chat-message-avatar"><Sparkles size={17}/></div><div className="chat-message-content"><div className="chat-author">NEXT STEP · अगला कदम</div><p>{view.chatQuestion.text}</p>{view.chatQuestion.choices&&<div className="chat-choices">{view.chatQuestion.choices.map(choice=><button disabled={!!busy} key={choice} onClick={()=>send(choice)}>{choice}<ArrowRight size={14}/></button>)}</div>}</div></article>}
      {!session.user&&<section className="chat-inline-card chat-signin"><LockKeyhole size={21}/><div><h2>Let’s keep your information private.</h2><p>{session.mode==="local"?"This workspace uses fictional sample information only. No real taxpayer accounts will be accessed.":"Sign in before we process taxpayer information."}</p>{session.mode==="local"?<button className="button secondary" disabled={!!busy} onClick={startLocal}>Start sample session</button>:<Link className="button" href="/login">Sign in securely <ArrowRight size={16}/></Link>}</div></section>}
      {showConsent&&session.user&&<section className="chat-inline-card chat-consent"><ShieldCheck size={22}/><div><h2>Your permission comes first.</h2><p>Allow Saral to store and process this tax conversation securely. Access to your Income Tax, employer or bank records requires separate authorization. {session.mode==="local"?"Use fictional data in this local workspace.":""}</p><div className="button-row"><button className="button" disabled={!!busy} onClick={begin}>Agree & start conversation <ArrowRight size={16}/></button><Link href="/privacy" className="text-button">Privacy details</Link></div></div></section>}
      {f&&view?.chatQuestion?.id!=="pan"&&<section className="chat-records-card"><div className="chat-card-heading"><span className="chat-connection-icon"><Link2 size={19}/></span><div><h2>Your records, connected.</h2><p>जानकारी अपने स्रोत से · We never treat missing data as zero.</p></div></div><div className="chat-record-list">{c.connections.map(source=><div key={source.kind}><span className={`record-state ${source.status}`}>{source.status==="ready"?<Check size={14}/>:source.status==="authorization_required"?<LockKeyhole size={13}/>:<span/>}</span><div><strong>{connectionLabels[source.kind]}</strong><small>{source.detail}</small></div><span className="connection-status">{source.status==="ready"?"Received":source.status==="authorization_required"?"Your permission":source.status==="unavailable"?"Not connected":source.status==="error"?"Try again":"Not requested"}</span>{source.authorizationUrl&&<a href={source.authorizationUrl} target="_blank" rel="noreferrer" className="text-button">Authorize <ArrowUpRight size={14}/></a>}</div>)}</div><p className="chat-consent-copy">By continuing, you authorize the configured providers to request this year’s records. Complete any provider verification securely; never put an OTP or password in chat.</p><div className="button-row"><button className="button secondary" disabled={!!busy||Boolean(locked)} onClick={connect}><Link2 size={16}/>{c.fetchAttemptedAt?"Refresh connected records":"Authorize & fetch records"}</button><Link className="text-button" href="/connections">Required connections <ArrowUpRight size={14}/></Link></div></section>}
      {f&&!aiAllowed&&!locked&&<section className="chat-ai-consent"><Sparkles size={17}/><p>Let the AI interpret the answers you choose to send. PAN and portal authorization are handled separately. <Link href="/privacy">Processing details</Link></p><button disabled={!session.aiConfigured} onClick={()=>setAiConsent(true)}>{session.aiConfigured?"Allow AI answers":"AI not configured"}</button></section>}
      {f&&view?.chatCanReview&&<section className="chat-review-card"><span className="chat-review-kicker"><FileCheck2 size={17}/> PREPARED FROM YOUR RECORDS & ANSWERS</span><h2>Here’s what I’ve prepared.</h2><p>एक बार जाँच लें। Your tax details are already filled behind the scenes. To correct anything, just tell me in the chat.</p>{currentEstimate&&<div className="chat-tax-overview"><div><span>Core tax estimate</span><strong>{inr(currentEstimate.coreTaxLiability)}</strong></div><div><span>{currentEstimate.estimatedRefund?"Estimated refund":"Estimated balance"}</span><strong>{inr(currentEstimate.estimatedRefund||currentEstimate.estimatedPayable)}</strong></div><div><span>Proposed regime</span><strong className="regime-name">{proposedRegime==="new"?"New regime":"Old regime"}</strong></div></div>}<p className="microcopy">Before filing-date adjustments, fees and unresolved claims. Tax is calculated by rules, not by GPT.</p><button className="chat-disclosure" onClick={()=>setShowReview(!showReview)} aria-expanded={showReview}>Read all prepared details <ChevronDown size={17}/></button>{showReview&&<dl className="chat-facts">{view.chatFacts.map((fact,i)=><div key={`${fact.label}-${i}`}><dt>{fact.label}</dt><dd>{fact.value}</dd></div>)}</dl>}<button className="button" disabled={!!busy||!showReview} onClick={()=>run("Recording your approval",async()=>accept(await post<FilingView>(`filings/${f.id}/chat-review`,{confirmed:true,hash:view.chatReviewHash})))}>{f.status==="prepared"?"Approve the latest summary":"I’ve checked it — approve this summary"}<Check size={16}/></button></section>}
      {f?.status==="prepared"&&<section className="chat-inline-card chat-filing-result"><ShieldCheck size={23}/><div><h2>{view?.filingIssues.some(x=>x.severity==="error")?"Prepared. Official filing is still pending.":"Ready for your filing approval."}</h2><p>Your summary is approved. Submission still needs official validation, your authorization and e-verification.</p><details><summary>See the checks still required</summary><ul>{view?.filingIssues.map((x,i)=><li key={i}>{x.message}</li>)}</ul></details><label className="check-row"><input type="checkbox" checked={submissionConsent} disabled={view?.filingIssues.some(x=>x.severity==="error")} onChange={e=>setSubmissionConsent(e.target.checked)}/><span>I authorize submission of this exact reviewed return.</span></label><button className="button" disabled={!!busy||!submissionConsent||view?.filingIssues.some(x=>x.severity==="error")} onClick={()=>run("Submitting through the official filing service",async()=>accept(await post<FilingView>(`filings/${f.id}/submit`,{confirmSubmission:true,hash:view!.reviewHash})))}>File my approved ITR <ArrowRight size={16}/></button><a className="text-button" href={`/api/filings/${f.id}/export`}><Download size={16}/> Download prepared worksheet</a></div></section>}
      {f?.officialReference&&<section className="chat-inline-card"><CheckCircle2 size={24}/><div><h2>Official submission received.</h2><p>Complete e-verification to finish the official workflow.</p><button className="button" onClick={()=>run("Opening official verification",async()=>{const result=await post<{redirectUrl?:string}>(`filings/${f.id}/e-verify`,{});if(result.redirectUrl)window.location.assign(result.redirectUrl);})}>Continue e-verification</button><button className="text-button" onClick={()=>run("Checking the official acknowledgement",async()=>{await post(`filings/${f.id}/acknowledgement`,{});accept(await api<FilingView>(`filings/${f.id}`));})}>Get acknowledgement</button>{f.acknowledgement&&<div className="notice success">Official acknowledgement: {f.acknowledgement.number}<br/>{new Date(f.acknowledgement.receivedAt).toLocaleString("en-IN")}</div>}</div></section>}
      {busy&&<div className="chat-thinking" role="status"><Loader2 className="spin" size={17}/>{busy}…</div>}
      {error&&<div className="error chat-error" role="alert">{error}<button onClick={()=>setError("")} aria-label="Dismiss message"><X size={15}/></button></div>}
      <div ref={bottom}/>
    </div>
    <div className={`chat-composer-wrap ${noMessages?"intro-composer":""}`}><div className="chat-composer"><label className="sr-only" htmlFor="chat-answer">Message Saral</label><textarea ref={input} id="chat-answer" rows={2} value={text} maxLength={6000} onChange={e=>setText(e.target.value)} disabled={Boolean(locked)||Boolean(busy)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void send();}}} placeholder={f?"Tell me here… / यहीं बताइए…":"I need to file my ITR… / मुझे ITR भरना है…"}/><div className="composer-bottom"><span><LockKeyhole size={12}/> Your records. Your permission.</span><div><button className="composer-mic" aria-label="Open voice call" disabled={!!busy||Boolean(locked)||!session.voiceConfigured} onClick={()=>{if(f)voiceSession.openCall({filingId:f.id,demo:Boolean(f.demo),label:`Your return · AY ${f.year}`});else setError("Start a conversation before opening voice.");}}><Mic size={20}/></button><button className="composer-send" aria-label="Send message" disabled={!text.trim()||!!busy||Boolean(locked)} onClick={()=>send()}><SendHorizontal size={20}/></button></div></div></div><p className="composer-caption">English, हिंदी or Hinglish · Voice updates your draft while you browse</p></div>
    <div className="chat-bottom-trust"><ShieldCheck size={14}/><span>Nothing is filed without your approval. Acknowledgement comes from the official service.</span></div>
  </div>;
}

export function ConnectionsPage(){return <div className="guide-page"><span className="eyebrow">PAN-FIRST. FETCH-FIRST. CHAT ONLY FOR GAPS.</span><h1>The connections behind a simpler ITR.</h1><p>PAN identifies the taxpayer. Authorized connections supply the records; GPT interprets them and asks about what is still missing.</p><section className="card form-section"><h2>What needs to be connected?</h2><div className="guide-table">{[
  ["Official ERI / filing partner","Required for taxpayer consent, official prefill, validation, submission, e-verification and acknowledgement. Access requires an approved ERI or an authorized filing partner."],
  ["Employer payroll / HRMS","Required to retrieve employer-issued Form 16 or salary records automatically. Central departments, states and PSUs need their own supported integrations; no universal PAN-to-Form-16 API is configured."],
  ["Bank / financial-data partner","Optional, authorized access to supported savings/FD/loan information. Coverage depends on the institution and permitted purpose. An Account Aggregator route requires an eligible regulated FIU arrangement; it is not an open PAN lookup."],
  ["Lender / investment providers","Where supported, fetch loan-interest certificates, NPS or other evidence under consent. Records may not establish every deduction’s eligibility, so the chat asks only for unresolved facts."],
  ["OpenAI","Interprets supported records and natural-language answers. It does not unlock taxpayer accounts, determine authorization or perform final tax arithmetic."],
].map(([name,body])=><div key={name}><strong>{name}</strong><p>{body}</p></div>)}</div><div className="notice">Desired flow: “File my ITR” → PAN → required permissions → fetch records → ask only for gaps → review → authorize filing → e-verify → official acknowledgement. Complete supported records can eliminate factual questions; authorization and verification still apply.</div><a href="https://www.incometax.gov.in/iec/foportal/api-specifications" target="_blank" rel="noreferrer" className="text-button">Official ERI API overview <ArrowUpRight size={15}/></a></section><Link className="button" href="/">Back to my conversation <ArrowRight size={17}/></Link></div>;}
