"use client";
import Link from "next/link";
import {useCallback,useEffect,useRef,useState} from "react";
import {ArrowDown,ArrowRight,ArrowUpRight,AudioLines,BadgeCheck,Check,CheckCheck,ChevronDown,Download,FileCheck2,FileText,FileUp,IndianRupee,Landmark,Loader2,LockKeyhole,MessageCircle,Mic,Play,RotateCcw,SendHorizontal,ShieldCheck,Sparkles,Wallet,X} from "lucide-react";
import {api,post,type FilingView,type Session} from "./client-api";
import {connectionLabels,type Connection} from "@/lib/chat";
import {inr} from "@/lib/domain";
import {VoiceOrb} from "./voice-call";
import {useVoiceSession,VoiceDraftNotice} from "./voice-session";
import {ChatInterface} from "./chat-interface";
import {DemoUploadPanel} from "./demo-upload-panel";

const sourceIcons={employer:Landmark,tax:ShieldCheck,bank:Wallet,deductions:FileText};
const fictionalName=(filing?:FilingView["filing"])=>filing?.conversation?.profileDraft.name?.trim()||"Aarav Sharma";
const firstName=(name:string)=>name.split(/\s+/)[0]||"Aarav";
const initials=(name:string)=>name.split(/\s+/).slice(0,2).map(part=>part[0]||"").join("").toUpperCase();
function sourceStatus(source:Connection,filing:FilingView["filing"]){
  if(source.reference==="USER-UPLOAD")return "Uploaded · reviewed";
  if(source.kind==="bank"&&filing.salary.depositInterest===null)return "FD interest needed";
  if(source.kind==="deductions"&&filing.demo?.scenario==="upload-form16")return filing.scope.wantsDeductions===null?"Questions remaining":filing.declarations.loans.length?"Needs eligibility review":"Reviewed in conversation";
  if(source.status==="ready")return "Simulated · ready";
  return source.kind==="employer"?"Upload your sample":"Not connected";
}
export function DemoExperience({id,session,onSessionChange}:{id?:string;session:Session;onSessionChange:()=>Promise<void>}){
  const[view,setView]=useState<FilingView|null>(null),[loading,setLoading]=useState(Boolean(id)),[busy,setBusy]=useState(""),[error,setError]=useState(""),[text,setText]=useState(""),[scenario,setScenario]=useState<"complete"|"missing-interest"|"upload-form16">("upload-form16"),[allowAI,setAllowAI]=useState(false),[reviewOpen,setReviewOpen]=useState(false),[fetchStep,setFetchStep]=useState(-1);
  const[documentBusy,setDocumentBusy]=useState(false),[latestAnswer,setLatestAnswer]=useState("");
  const latest=useRef<FilingView|null>(null),composer=useRef<HTMLTextAreaElement>(null),fetchTimer=useRef<ReturnType<typeof setInterval>|null>(null),mounted=useRef(true);
  const accept=useCallback((v:FilingView)=>{const previous=latest.current;if(previous?.filing.id!==v.filing.id||previous?.chatReviewHash!==v.chatReviewHash)setReviewOpen(false);latest.current=v;setView(v);},[]);
  const voiceSession=useVoiceSession();
  const openVoice=(current=latest.current)=>{if(current)voiceSession.openCall({filingId:current.filing.id,demo:Boolean(current.filing.demo),label:`${current.filing.demo?fictionalName(current.filing)+" · Demo":"Your return"} · AY ${current.filing.year}`});};
  useEffect(()=>{const update=voiceSession.lastUpdate;if(update&&update.filingId===(latest.current?.filing.id??id)&&(!latest.current||update.view.filing.revision>latest.current.filing.revision))accept(update.view);},[voiceSession.lastUpdate,id,accept]);
  useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;if(fetchTimer.current)clearInterval(fetchTimer.current);};},[]);
  useEffect(()=>{let active=true;if(!id){setView(null);latest.current=null;setLoading(false);setError("");return;}setLoading(true);api<FilingView>(`filings/${id}`).then(v=>active&&accept(v)).catch(e=>active&&setError(e.message)).finally(()=>active&&setLoading(false));return()=>{active=false;};},[id,accept]);
  const f=view?.filing,c=f?.conversation;const demoName=fictionalName(f),demoFirstName=firstName(demoName);const finished=f?.demo?.phase==="verified",submitted=f?.demo?.phase==="submitted";const estimate=view?.estimates?.[view.recommendedRegime];const waitingForForm16=f?.demo?.scenario==="upload-form16"&&c?.connections.find(source=>source.kind==="employer")?.status!=="ready";
  const asksTan=view?.chatQuestion?.id==="salary.employerTan"||view?.chatQuestion?.id==="confirm:salary.employerTan";
  const activeStep=finished?3:submitted||f?.status==="prepared"||view?.chatCanReview?2:waitingForForm16||f?.pending||f?.demo?.phase==="created"?0:1;
  async function run(label:string,work:()=>Promise<void>){setBusy(label);setError("");try{await work();}catch(e){setError((e as Error).message);}finally{if(mounted.current)setBusy("");}}
  async function fetchRecords(current:FilingView){
    setFetchStep(0);let progress=0;const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    if(!reduced)fetchTimer.current=setInterval(()=>{progress=Math.min(3,progress+1);setFetchStep(progress);},430);
    try{const [next]=await Promise.all([post<FilingView>(`filings/${current.filing.id}/demo-fetch`,{confirmed:true,revision:current.filing.revision}),new Promise(r=>setTimeout(r,reduced?0:1900))]);if(mounted.current)accept(next);return next;}
    finally{if(fetchTimer.current)clearInterval(fetchTimer.current);setFetchStep(-1);}
  }
  async function start(withVoice=false){await run("Starting your demo",async()=>{
    const created=await post<FilingView>("demo/start",{scenario,consent:true});accept(created);await onSessionChange();window.history.replaceState(null,"",`/filings/${created.filing.id}`);setBusy("Simulating record retrieval");const ready=await fetchRecords(created);if(withVoice)openVoice(ready);
  });}
  async function send(answer=text):Promise<string>{
    const current=latest.current;if(!current)throw new Error("Start the demo first.");
    setBusy("Luna is thinking");setError("");
    try{const next=await post<FilingView>(`filings/${current.filing.id}/chat`,{text:answer,aiConsent:allowAI,revision:current.filing.revision});accept(next);setText("");
      const last=next.filing.conversation?.messages.at(-1)?.text??"Your demo details are updated.";
      setLatestAnswer(last);
      return last+(next.chatQuestion?"\n"+next.chatQuestion.text:" Your comparison is ready. Please read and approve the summary on screen.");
    }catch(e){setError((e as Error).message);throw e;}finally{setBusy("");}
  }
  async function sendTyped(answer=text){if(!answer.trim()||busy||documentBusy)return;if(!allowAI){setError("Enable AI chat below before sending your answer.");return;}try{await send(answer);}catch{}}
  function restart(){setView(null);latest.current=null;setText("");setError("");setLatestAnswer("");setAllowAI(false);setReviewOpen(false);window.history.replaceState(null,"","/");window.scrollTo({top:0,behavior:"smooth"});}
  if(loading&&!view)return <div className="demo-opening"><VoiceOrb small state="thinking"/><p>Opening your tax conversation…</p></div>;
  if(view&&!f?.demo)return <ChatInterface id={id} session={session} onSessionChange={onSessionChange}/>;
  return <div className={`demo-experience ${f?"has-conversation demo-workspace":""}`}>
    {!f?<><div className="demo-eyebrow"><span/> DESIGNED FOR THE PEOPLE WHO SERVE INDIA <small>INTERACTIVE DEMO</small></div>
      <section className="demo-hero"><div className="demo-hero-copy"><div className="hero-edition">SARAL / सरल <span>01 — THE TAX COMPANION</span></div><h1>Less paperwork.<br/>More <span>peace<br className="hero-break"/> of mind.</span></h1><p className="demo-hindi">अब टैक्स की बातें,<br/>बस बातों-बातों में।</p><p className="demo-description">One conversation. Your records, brought together.<br/>A return prepared with you, not paperwork handed to you.</p><div className="demo-hero-actions"><button className="button demo-primary" disabled={!!busy} onClick={()=>start()}><Play size={15} fill="currentColor"/> Experience the demo <ArrowRight size={18}/></button><button className="demo-voice-link" disabled={!!busy||!session.voiceConfigured} onClick={()=>start(true)}><AudioLines size={20}/> Talk to Saral</button></div><p className="demo-consent-caption">Fictional records. No real filing. AI runs only when you enable chat or voice.</p><div className="demo-scenario"><span>CHOOSE YOUR JOURNEY</span><div><button className={scenario==="upload-form16"?"selected":""} onClick={()=>setScenario("upload-form16")}>Upload sample Form 16 <FileUp size={13}/></button><button className={scenario==="complete"?"selected":""} onClick={()=>setScenario("complete")}>Everything connected <Check size={13}/></button><button className={scenario==="missing-interest"?"selected":""} onClick={()=>setScenario("missing-interest")}>Just one question <MessageCircle size={13}/></button></div></div></div>
      <div className="demo-hero-visual"><div className="visual-coordinate">INTELLIGENCE, IN YOUR SERVICE.</div><div className="hero-orb"><VoiceOrb state="idle"/></div><div className="orbit-caption"><span className="pulse-dot"/> READY WHEN YOU ARE <span>आपका साथी</span></div><div className="floating-record top"><span className="floating-icon"><FileCheck2 size={19}/></span><div><strong>Form 16, taken care of.</strong><small>Sample payroll connection</small></div><CheckCircle/></div><div className="floating-record bottom"><div><small>FICTIONAL RETURN PREVIEW</small><strong>Clarity. Down to the rupee.</strong><span>Both regimes. Every supported deduction.</span></div><IndianRupee size={25}/></div><div className="visual-grid-label">GOVERNMENT EMPLOYEES<br/>CENTRAL · STATE · PSU</div></div></section>
      <div className="demo-assurance"><span><ShieldCheck size={17}/> You approve every submission</span><span><LockKeyhole size={16}/> Private by design</span><span><AudioLines size={18}/> English · हिंदी · Hinglish</span><span><IndianRupee size={15}/> ₹21 proposed service fee</span></div>
      <section className="demo-process"><div className="process-title"><span>FROM “I NEED TO FILE”<br/>TO “THAT WAS SIMPLE.”</span><ArrowDown size={22}/></div>{[["01","We connect.","Your payroll, tax credits and bank information, together."],["02","We understand.","Only gaps become questions. You speak; we prepare."],["03","You’re in control.","A clear review, your approval, and a demo acknowledgement."]].map(([n,title,body])=><div className="process-step" key={n}><span>{n}</span><h2>{title}</h2><p>{body}</p></div>)}</section>
      <div className="demo-note"><span>BUILT WITH PURPOSE.</span><p>A public-service experience, with the simplicity of a conversation. This demo simulates official connections until ERI onboarding is complete.</p><Link href="/connections">What powers the real thing <ArrowUpRight size={16}/></Link></div></>:
      <><div className="conversation-heading"><div><span className="demo-eyebrow"><span/> YOUR TAX WORKSPACE · आपका टैक्स साथी</span><h1>नमस्ते, {demoFirstName}<span>.</span></h1><p>{finished?"Your demo receipt is ready.":activeStep===0?"Start with your Form 16. We’ll guide you from here.":activeStep===1?"Just a few details, one question at a time.":"Check your summary before you continue."}</p></div><div className="conversation-tools"><Link className="demo-state-link" href={`/filings/${f.id}/status`}>Journey status · स्थिति</Link><button className="voice-launch" onClick={()=>openVoice()} disabled={!!busy||documentBusy||!session.voiceConfigured||submitted||finished||!!f.pending}><AudioLines size={19}/> Voice call</button><button className="restart-button" onClick={restart} aria-label="Start a new demo"><RotateCcw size={18}/></button></div></div>
      <div className="demo-progress" aria-label="Filing progress">{["Form 16","Questions","Review","Demo receipt"].map((label,i)=><span key={label} aria-current={i===activeStep?"step":undefined} className={i<activeStep?"reached":i===activeStep?"current":""}><span>{i<activeStep||finished?<Check size={13}/>:String(i+1).padStart(2,"0")}</span>{label}</span>)}</div>
      <div className="demo-conversation-layout"><section className="demo-conversation-main">
      <VoiceDraftNotice filingId={f.id} revision={f.revision}/>
      {(f.demo?.phase==="created"||fetchStep>=0)&&<div className="demo-fetch-panel"><div className="fetch-title"><span className="sim-label">SIMULATION</span><strong>Bringing your records together.</strong></div>{["Employer Form 16","Tax credits & prefill","Bank interest","Eligible deductions"].map((label,i)=><div className={i<=fetchStep?"active":""} key={label}><span>{i<fetchStep?<Check size={14}/>:i===fetchStep?<Loader2 size={14} className="spin"/>:String(i+1).padStart(2,"0")}</span>{label}<small>{i<fetchStep?"Demo record ready":i===fetchStep?"Simulating connection":"Next"}</small></div>)}{fetchStep<0&&<button className="button" onClick={()=>run("Simulating record retrieval",async()=>{await fetchRecords(view!);})}>Connect demo records <ArrowRight size={16}/></button>}</div>}
      {!submitted&&!finished&&f.demo?.phase==="records_ready"&&<DemoUploadPanel key={f.id} view={view!} onChange={accept} onBusyChange={setDocumentBusy} uploadFirst={f.demo.scenario==="upload-form16"}/>}
      {latestAnswer&&!f.pending&&!submitted&&!finished&&<div className="demo-latest-answer" role="status"><Check size={17}/><p>{latestAnswer}</p></div>}
      {f.demo?.phase==="records_ready"&&!f.pending&&!waitingForForm16&&view?.chatQuestion&&<section className="demo-question" aria-label="Current question"><span>ONE DETAIL AT A TIME · बस एक बात</span><h2>{asksTan?"Check the employer TAN":view.chatQuestion.id==="salary.depositInterest"?`Just one thing, ${demoFirstName}.`:view.chatQuestion.id==="demo.homeLoan"?"Any home loan to tell us about?":"A quick clarification."}</h2><p>{view.chatQuestion.text}</p>{asksTan&&<div className="demo-tan-help"><code><b>DEMO</b><span>12345</span><b>A</b></code><small>Bundled fictional sample: the fourth character is the letter <strong>O</strong>.</small><button disabled={!!busy||documentBusy||!allowAI} onClick={()=>sendTyped("DEMO12345A")}>Use bundled sample TAN <ArrowRight size={15}/></button></div>}{view.chatQuestion.id==="salary.depositInterest"&&<button disabled={!!busy||documentBusy||!allowAI} onClick={()=>sendTyped("My annual FD interest was 18000 rupees according to the bank interest statement.")}>₹18,000 from my FD <ArrowRight size={15}/></button>}{view.chatQuestion.id!=="salary.depositInterest"&&view.chatQuestion.choices?.map(choice=><button key={choice} disabled={!!busy||documentBusy||!allowAI} onClick={()=>sendTyped(choice)}>{choice} <ArrowRight size={15}/></button>)}</section>}
      {view?.chatCanReview&&f.status!=="prepared"&&estimate&&<section className="demo-summary"><div className="summary-eyebrow"><BadgeCheck size={17}/> YOUR DEMO RETURN IS PREPARED</div><h2>Some clarity.<br/><span>A little peace of mind.</span></h2><div className="summary-money"><div><span>{estimate.estimatedRefund?"Estimated refund":"Estimated tax balance"}</span><strong>{inr(estimate.estimatedRefund||estimate.estimatedPayable)}</strong><small>Core estimate · fictional sample data</small></div><div className="summary-regime"><span>LOWER CORE TAX</span><strong>{view.recommendedRegime==="new"?"New regime":"Old regime"}</strong><small>Calculated by tax rules</small></div></div><div className="regime-comparison"><div><span>New regime</span><strong>{inr(view.estimates!.new.coreTaxLiability)}</strong></div><div><span>Old regime</span><strong>{inr(view.estimates!.old.coreTaxLiability)}</strong></div></div><p>Filing-date adjustments and official validation are simulated in this demo. No refund is being initiated.</p><button className="summary-expand" disabled={!!busy} aria-expanded={reviewOpen} onClick={()=>setReviewOpen(!reviewOpen)}>Read the prepared details <ChevronDown size={16}/></button>{reviewOpen&&<dl className="demo-review-facts">{view.chatFacts.map((fact,i)=><div key={i}><dt>{fact.label}</dt><dd>{fact.value}</dd></div>)}</dl>}<button className="button demo-primary" disabled={!!busy||!reviewOpen} onClick={()=>run("Saving your approval",async()=>accept(await post<FilingView>(`filings/${f.id}/chat-review`,{confirmed:true,hash:view.chatReviewHash})))}>I’ve checked it. Approve summary <Check size={16}/></button></section>}
      {f.status==="prepared"&&f.demo?.phase==="records_ready"&&<section className="demo-next-step"><div className="step-badge"><ShieldCheck size={27}/></div><span className="sim-label">SIMULATED SUBMISSION</span><h2>You’ve checked it.<br/>Let’s complete the demo.</h2><p>This sends the reviewed snapshot to our simulator, never to the Income Tax Department. You will not be charged.</p><button className="button demo-primary" disabled={!!busy} onClick={()=>run("Simulating submission",async()=>accept(await post<FilingView>(`filings/${f.id}/demo-submit`,{confirmed:true,hash:view!.reviewHash,revision:f.revision})))}>Simulate filing my ITR <ArrowRight size={17}/></button><Link className="demo-state-link" href={`/filings/${f.id}/payment`}>About the proposed ₹21 fee</Link></section>}
      {submitted&&<section className="demo-next-step"><div className="step-badge"><CheckCheck size={27}/></div><span className="sim-label">SIMULATED E-VERIFICATION</span><h2>One last step.<br/>Your confirmation.</h2><p>In the live service, you complete an official verification method. Here, this button simulates that confirmation. No OTP is requested.</p><button className="button demo-primary" disabled={!!busy} onClick={()=>run("Creating the demo receipt",async()=>accept(await post<FilingView>(`filings/${f.id}/demo-verify`,{confirmed:true,revision:f.revision})))}>Complete demo verification <Check size={17}/></button></section>}
      {finished&&f.demo?.acknowledgement&&<section className="demo-receipt"><div className="receipt-confetti" aria-hidden="true">{Array.from({length:16},(_,i)=><i key={i} style={{"--i":i} as React.CSSProperties}/>)}</div><div className="receipt-check"><Check size={32}/></div><span>DEMO JOURNEY COMPLETE · डेमो पूरा हुआ</span><h2>And just like that,<br/><em>you’re done.</em></h2><p>Your simulated acknowledgement is ready.</p><div className="receipt-paper"><div><strong>saral.</strong><span>DEMO RECEIPT</span></div><dl><div><dt>Sample taxpayer</dt><dd>{demoName}</dd></div><div><dt>Assessment year</dt><dd>2026–27</dd></div><div><dt>Demo reference</dt><dd>{f.demo.acknowledgement.number}</dd></div><div><dt>Core refund estimate</dt><dd>{estimate?inr(estimate.estimatedRefund):"—"}</dd></div></dl><div className="receipt-watermark">NOT FILED WITH THE INCOME TAX DEPARTMENT</div></div><div className="receipt-actions"><a className="button demo-primary" href={`/api/filings/${f.id}/demo-receipt`}><Download size={16}/> Download demo receipt</a><button onClick={restart}>Try another scenario <RotateCcw size={15}/></button></div><small>Fictional data. No official filing, payment or refund took place.</small></section>}
      {busy&&<div className="demo-thinking" role="status"><span/><span/><span/><p>{busy}…</p></div>}{error&&<div className="error" role="alert">{error}<button className="icon-button" aria-label="Dismiss error" onClick={()=>setError("")}><X size={15}/></button></div>}
      {!submitted&&!finished&&!f.pending&&!waitingForForm16&&f.demo?.phase!=="created"&&<div className="demo-composer-section">{!allowAI&&<div className="demo-ai-permission"><ShieldCheck size={18}/><p>Send your chosen answers to OpenAI; explanations may also use Gemini. Fictional data only.</p><button onClick={()=>setAllowAI(true)}>Enable AI chat</button></div>}<label className="demo-composer-title" htmlFor="demo-message">{view?.chatQuestion?"Your answer · आपका जवाब":"Ask or change a detail · कुछ बदलना है?"}</label><div className="demo-composer"><textarea ref={composer} id="demo-message" aria-label="Message Saral" rows={2} value={text} maxLength={6000} disabled={!!busy||documentBusy} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void sendTyped();}}} placeholder={asksTan?"Enter the employer TAN exactly as printed…":"Type your answer, or speak in Hindi…"}/><div><span><LockKeyhole size={13}/> Saved only to this draft</span><button aria-label="Open voice call" onClick={()=>openVoice()} disabled={!session.voiceConfigured||!!busy||documentBusy}><Mic size={19}/></button><button className="demo-send" aria-label="Send message" disabled={!!busy||documentBusy||!text.trim()||!allowAI} onClick={()=>sendTyped()}><SendHorizontal size={19}/></button></div></div><details className="demo-edit-tips"><summary>How to change a name or amount</summary><p>Try “My name in this demo is Meera Sharma” or “Correct my annual salary to ₹12,00,000.” Changes need a fresh review.</p></details></div>}
      <details className="demo-history"><summary><MessageCircle size={17}/> Conversation history <span>{c?.messages.length??0} messages</span><ChevronDown size={16}/></summary><div className="demo-messages" role="log" aria-label="Demo conversation">{c?.messages.map(m=><div key={m.id} className={`demo-message ${m.role}`}><div className="demo-message-icon">{m.role==="assistant"?<Sparkles size={16}/>:initials(demoName).slice(0,1)}</div><div><span>{m.role==="assistant"?"SARAL · सरल":`${demoName.toLocaleUpperCase("en-IN")} · DEMO USER`}</span><p>{m.text}</p></div></div>)}</div></details>
      </section><aside className="demo-context"><div className="demo-profile"><div className="profile-initial">{initials(demoName)}</div><div><strong>{demoName}</strong><span>FICTIONAL DEMO PROFILE</span></div></div><div className="context-records"><span>YOUR RECORDS · आपके रिकॉर्ड</span>{c?.connections.map(source=>{const Icon=sourceIcons[source.kind];return <div key={source.kind}><Icon size={18}/><div><strong>{connectionLabels[source.kind]}</strong><small>{sourceStatus(source,f)}</small></div>{source.status==="ready"&&!(source.kind==="bank"&&f.salary.depositInterest===null)&&<Check size={14}/>}</div>;})}</div><div className="context-voice"><AudioLines size={24}/><h3>हिंदी में बात करें</h3><p>You can answer by voice.</p><button onClick={()=>openVoice()} disabled={!session.voiceConfigured||!!busy||documentBusy||submitted||finished||!!f.pending}><Mic size={17}/> Call your tax companion</button></div><div className="context-note"><ShieldCheck size={17}/><p>Private sample workspace. Nothing is filed without your review.</p></div></aside></div></>}
    {!f&&error&&<div className="error" role="alert">{error}</div>}{!f&&busy&&<div className="demo-thinking"><Loader2 className="spin" size={18}/><p>{busy}…</p></div>}

  </div>;
}
function CheckCircle(){return <span className="floating-check"><Check size={12}/></span>;}
